# Generated by Django 4.2.6 on 2024-02-06 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
